### ISSUE TITLE
API Links not working

### ISSUE THREAD

**Issue by nkosi-tauro** [akabab/starwars-api#1]
Both the Cached [Link ](https://cdn.rawgit.com/akabab/starwars-api/0.2.1/api) and Base [Url](https://akabab.github.io/starwars-api/api) are returning a 404 error

**Comment by akabab** [comment]
CDN url has been changed (since rawgit has closed their services)
fixed in 563a785

**Following the base url or cdn url, you should specify a valid route:**

- **/all.json**
https://akabab.github.io/starwars-api/api/all.json
or
https://rawcdn.githack.com/akabab/starwars-api/0.2.1/api/all.json

- **/id/{id}.json**
https://akabab.github.io/starwars-api/api/all.json
or
https://rawcdn.githack.com/akabab/starwars-api/0.2.1/api/id/1.json
